### ISSUE TITLE
Use garyburd/go-oauth instead of matryer/go-oauth

### ISSUE THREAD

**Issue by chilts** [machinebox/twitterfeed#2]
I can see that github.com/matryer/go-oauth is a fork of github.com/garyburd/go-oauth and whilst it probably works fine, is it worth switching to the original, mainly because that looks like it is maintained (updated 9 hours ago) a bit more than Mat's fork (updated three years ago).

**Comment by dahernan** [comment]
Just updated on master, thanks!

**Comment by chilts** [comment]
Sweet thanks. :)
